services:

# DB database mysql (db-web)
  db_web:
    image: mysql:8.0.32
    volumes:
      - ./db:/var/run/mysqld:rw
    user: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    container_name:  db_web
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 33160:3306

# Server apache per sviluppo html
  apache:
    image: httpd:latest
    container_name: my-apache-app
    volumes:
      - ./:/usr/local/apache2/htdocs
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 8081:80

# webdev (sviluppo php)
  webdev:
    container_name: webdev
    depends_on:
      - db_web
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: php -S 0.0.0.0:82 -t /progetti
    environment:
      XDEBUG_MODE: develop,debug
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
    volumes:
      - ./php/progetti:/progetti # cartella progetto
      - ./php/xdebug/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini # impostazioni per debug
      - ./php/php.ini:/usr/local/etc/php/php.ini # impostazioni php
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 8200:82
